apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  selector:
    name: deployment1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort

